package com.amir.dreamshops.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.sql.Blob;

@Entity//The @Entity annotation is used to specify that the class is an entity and is mapped to a database table
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Image {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //GenerationType.IDENTITY indicates that the primary key
    // should be generated by the database itself, typically using an auto-incremented column.
    // This strategy is often used when you want the database to handle the generation of unique primary key
    // values for new records.
    private Long id;
    private String fileName;
    private String fileType;
    @Lob // This annotation is used to inform the JPA provider that the field may hold a large amount of data
    // and should be handled accordingly in the database.
    private Blob image;
    private String downloadUrl;

    @ManyToOne  //it indicates that many Image entities can be associated with one Product entity.
    @JoinColumn(name="product_id")// The @JoinColumn annotation is used to specify the foreign key column in
    // the Image table that references the primary key of the Product table. The name="product_id" attribute
    // specifies the name of this foreign key column. This annotation ensures that the product field in the
    // Image entity is mapped to the product_id column in the database table.
    private  Product product;

}
